name: Deploy Frontend & Backend

on:
  push:
    branches:
      - development

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check for Changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  deploy-frontend:
    needs: check-changes
    if: needs.check-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            set -e
            echo "🚀 Deploying frontend..."

            cd ~
            if [ -d "repo/.git" ]; then
              echo "✅ Repository exists. Pulling latest changes..."
              cd repo
              git reset --hard
              git clean -fd
              git checkout development
              git pull origin development
            else
              echo "📦 Cloning repository..."
              rm -rf repo
              git clone git@github.com:AdviceFit/AdviceFit.git repo
              cd repo
            fi

            cd frontend
            echo "📥 Installing dependencies..."
            npm install
            echo "🛠️ Building the frontend..."
            npm run build
            echo "🔁 Restarting frontend with pm2..."
            pm2 restart frontend || pm2 start npm --name "frontend" -- start --watch

  deploy-backend:
    needs: check-changes
    if: needs.check-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            set -e
            echo "🚀 Deploying backend..."

            if [ -d "~/repo/.git" ]; then
              echo "✅ Repository exists. Pulling latest changes..."
              cd ~/repo
              git reset --hard
              git clean -fd
              git checkout development
              git pull origin development
            else
              echo "📦 Cloning repository..."
              rm -rf ~/repo
              git clone git@github.com:AdviceFit/AdviceFit.git ~/repo
            fi

            echo "📂 Navigating to backend directory..."
            cd ~/repo/backend

            echo "📥 Installing dependencies..."
            npm ci

            echo "🔁 Restarting backend with pm2..."
            pm2 restart backend || pm2 start npm --name "backend" -- start
